const { createInteractionRouter } = require('./interactionRouter');

// `handlers.js` is the public composition root. Some flow tests and operational
// reload tools intentionally clear only this module from Node's require cache;
// rebuilding the runtime here preserves the former singleton lifecycle.
delete require.cache[require.resolve('./handlerRuntime')];
const runtime = require('./handlerRuntime');

const handleInteractionCreate = createInteractionRouter(runtime.routingDependencies);

module.exports = {
  buildTodayMissionNoticePayload: runtime.buildTodayMissionNoticePayload,
  createAdminMissionHubEmbed: runtime.createAdminMissionHubEmbed,
  createAdminShopHubEmbed: runtime.createAdminShopHubEmbed,
  createNoticeEmbed: runtime.createNoticeEmbed,
  createOperationSummaryEmbed: runtime.createOperationSummaryEmbed,
  createPendingRedemptionsEmbed: runtime.createPendingRedemptionsEmbed,
  createPendingSubmissionsEmbed: runtime.createPendingSubmissionsEmbed,
  createMissionHubPayload: runtime.createMissionHubPayload,
  createShopHubPayload: runtime.createShopHubPayload,
  getOperatorHubEmbed: runtime.getOperatorHubEmbed,
  handleChannelGuideCommand: runtime.handleChannelGuideCommand,
  handleCheckinCommand: runtime.handleCheckinCommand,
  handleDungeonworldButton: runtime.handleDungeonworldButton,
  handleDmSafetyReviewButton: runtime.handleDmSafetyReviewButton,
  handleDungeonworldCommand: runtime.handleDungeonworldCommand,
  handleDungeonworldManageButton: runtime.handleDungeonworldManageButton,
  handleDungeonworldManageCommand: runtime.handleDungeonworldManageCommand,
  handleDungeonworldRecordCommand: runtime.handleDungeonworldRecordCommand,
  handleGuideCommand: runtime.handleGuideCommand,
  handleGuideHubSelect: runtime.handleGuideHubSelect,
  handleWebgameLinkCommand: runtime.handleWebgameLinkCommand,
  handleWebgameRankingCommand: runtime.handleWebgameRankingCommand,
  handleInteractionCreate,
  handleMissionHubButton: runtime.handleMissionHubButton,
  handleMissionHubModal: runtime.handleMissionHubModal,
  handleMissionHubSelect: runtime.handleMissionHubSelect,
  handleMissionManageCommand: runtime.handleMissionManageCommand,
  handleMissionCommand: runtime.handleMissionCommand,
  handleMissionSelect: runtime.handleMissionSelect,
  handleMissionSubmissionModal: runtime.handleMissionSubmissionModal,
  handleNoticeCommand: runtime.handleNoticeCommand,
  handleOperationStatusCommand: runtime.handleOperationStatusCommand,
  handleOperatorHubSelect: runtime.handleOperatorHubSelect,
  handleOperationExportCommand: runtime.handleOperationExportCommand,
  handleParticipantMenuButton: runtime.handleParticipantMenuButton,
  handlePointLogCommand: runtime.handlePointLogCommand,
  handlePointManageCommand: runtime.handlePointManageCommand,
  handlePointCommand: runtime.handlePointCommand,
  handleQuestionCommand: runtime.handleQuestionCommand,
  handleRediCommand: runtime.handleRediCommand,
  handleRediContactCommand: runtime.handleRediContactCommand,
  handleRediHelpCommand: runtime.handleRediHelpCommand,
  handleRediRulesCommand: runtime.handleRediRulesCommand,
  handleRediScheduleCommand: runtime.handleRediScheduleCommand,
  handleRedemptionCommand: runtime.handleRedemptionCommand,
  handleRedemptionConfirmButton: runtime.handleRedemptionConfirmButton,
  handleRedemptionManageCommand: runtime.handleRedemptionManageCommand,
  handleShopHubButton: runtime.handleShopHubButton,
  handleShopHubModal: runtime.handleShopHubModal,
  handleShopHubSelect: runtime.handleShopHubSelect,
  handleShopSelect: runtime.handleShopSelect,
  handleSubmissionCommand: runtime.handleSubmissionCommand,
  handleSubmissionManageCommand: runtime.handleSubmissionManageCommand,
  handleSubmissionReviewButton: runtime.handleSubmissionReviewButton,
  handleShopManageCommand: runtime.handleShopManageCommand,
  handleShopCommand: runtime.handleShopCommand,
};
